### ISSUE TITLE
Feature Request: Lore Items

### ISSUE THREAD

**Issue by tbstewa** [JustBru00/RenamePlugin#10]
Hello,
I am using a custom enchantment plugin and only want users to add lore not related to the custom enchants. Is there a way to make a special item that contains the lore and would be crafted or dragged onto the item to change the lore? With maybe a black/whitelist of what the lore can contain? I would greatly appreciate this if it became a feature!

**Comment by JustBru00** [comment]
How many blacklisted words would you need? I can make a section that checks if the lore being imputed contains a certain word it will block it.

**Comment by tbstewa** [comment]
I need about 25... but what about a separate config, or a section within the config where it says "Blacklist:" and then it leaves it available for me to list as many items to the blacklist as I want?

**Comment by JustBru00** [comment]
I was thinking about that I will try to add it in the next update.

**Comment by JustBru00** [comment]
I will work on this for version 2.3

**Comment by JustBru00** [comment]
Do you want the plugin to block the rename completely or remove that word?

**Comment by JustBru00** [comment]
I would like to start coding this today so if you cloud answer my question that would be nice. 
I will be using the block the rename completly method if you don't respond. 

Thanks,
Justin

**Comment by JustBru00** [comment]
Added a blacklist. Will test tommorrow
