### ISSUE TITLE
Using Backslash \ in lores creates two \\

### ISSUE THREAD

**Issue by SiuanSong** [JustBru00/RenamePlugin#100]
As the title states, if you enter in a backslash in a lore, it creates a double \\ in the lore.  Same goes for rename.

**Comment by JustBru00** [comment]
Probably an issue with Java escaping special characters.

**Comment by JustBru00** [comment]
Possible solution is replacing double // with /. Although that could break users attempting to use an actual //.

**Comment by JustBru00** [comment]
@SiuanSong Just to check, are you using EpicRename version 3.5?
Also what minecraft version are you running the plugin on?

**Comment by JustBru00** [comment]
/rename appears to work as expected. 
![image](https://user-images.githubusercontent.com/11063799/49346926-0920a980-f667-11e8-87f2-5f43c3f799f2.png)


![image](https://user-images.githubusercontent.com/11063799/49346931-1342a800-f667-11e8-8a8d-21e2fffe04e5.png)

**Comment by JustBru00** [comment]
Closing issue as I have not gotten any additional information. I will reopen this issue if more details are are available in the future.
