### ISSUE TITLE
Add economy cost for /glow

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#101]
From https://www.spigotmc.org/threads/epicrename.51650/page-13#post-3242768
![image](https://user-images.githubusercontent.com/11063799/49618897-4008ff00-f988-11e8-9668-33362cf3c83e.png)

Requested by danechek on spigotmc.org

**Comment by danechek** [comment]
how long to wait for the updates of the plugin with this function?

**Comment by JustBru00** [comment]
Will be released in the upcoming version 3.6 update.
