### ISSUE TITLE
Not appearing

### ISSUE THREAD

**Issue by xNoraInfinita** [JustBru00/RenamePlugin#11]
I have vault and an up to date spigot version but the plugin doesn't come up in the list of plugins, and the command is not recognized.

**Comment by JustBru00** [comment]
Do you get any errors while loading the server?

**Comment by xNoraInfinita** [comment]
I get this error

![](http://i.imgur.com/Pqkrqxs.png)

**Comment by JustBru00** [comment]
Are you using Java 8 on your server?

If your server is using Java 7 try this version: https://www.dropbox.com/s/nejlkkvb7doni72/EpicRename%20v2.3%20JAVA%207.jar?dl=0

**Comment by xNoraInfinita** [comment]
How do I check this?

**Comment by JustBru00** [comment]
Try downloading the plugin from the link I sent and see if that works on your server.

**Comment by xNoraInfinita** [comment]
Yes this version did work

**Comment by JustBru00** [comment]
So that was your problem, your server host is running Java 7. I will most likely be changing the normal plugin updates to Java 7.
