### ISSUE TITLE
Add a /removename and a /removelore command

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#117]
Requested by @mechcalvin on spigotmc.org. https://www.spigotmc.org/threads/epicrename.51650/page-16#post-3541002
![image](https://user-images.githubusercontent.com/11063799/64208104-18d65400-ce6c-11e9-9c3f-7119a1f8963c.png)

**Comment by JustBru00** [comment]
This will need to copy the durability of the previous item over for /removename.

**Comment by JustBru00** [comment]
Requested by `LOOHP` on spigotmc.org. **https://www.spigotmc.org/threads/epicrename.51650/page-20#post-4369372**
![image](https://user-images.githubusercontent.com/11063799/155425482-98c91960-a108-49d3-943b-47d7b97c7e1e.png)

**Comment by LOOHP** [comment]
> This will need to copy the durability of the previous item over for /removename.

I believe `ItemMeta.setDisplayName(null);` clears the display name of an item.

**Comment by JustBru00** [comment]
> > This will need to copy the durability of the previous item over for /removename.
> 
> I believe `ItemMeta.setDisplayName(null);` clears the display name of an item.

I will have to check that out. I can't tell from the spigot docs.

**Comment by LOOHP** [comment]
`hasDisplayName()` just checks whether the display name is null under the hood in CraftItemMeta
![image](https://user-images.githubusercontent.com/22975196/155427087-4c55f81c-75d1-47df-98b8-97c22bf25800.png)

And during `ItemStack.setItemMeta(ItemMeta);` Bukkit just uses `hasDisplayName()` to decide whether there is a display name or not, also in CraftItemMeta
![image](https://user-images.githubusercontent.com/22975196/155427217-286d0894-719f-41e9-94a0-bc21e3f4fa8e.png)

**Comment by JustBru00** [comment]
That might work then. Thanks for the info.

**Comment by LOOHP** [comment]
Sorry for the bump but, any updates on this request? :)

**Comment by JustBru00** [comment]
Sorry for the delay on this request. My work has been keeping me busy all summer. I will try to get this feature finished in the next week or two.

**Comment by LOOHP** [comment]
No problem, please take your time. :)

**Comment by LOOHP** [comment]
Thank you!

**Comment by JustBru00** [comment]
Closed by c042c8d4cccce49c97c6c7eae729cc51ce8af623
