### ISSUE TITLE
Feature: /InsertLoreline

### ISSUE THREAD

**Issue by Venaf** [JustBru00/RenamePlugin#118]
The plugin conflicts a bit with Runecraft, because it uses lore to track their own runic enchantments.  We can delete lines individually, but can't insert a line before another (Runecraft puts them all in the last lore line).  Could we get an option to insert a line and move all other lines down?

**Comment by JustBru00** [comment]
I think that is a great idea. I will add it to the list for EpicRename version 3.7.

`/insertloreline <beforeLineNumber> <loreText>`
`/insertloreline 2 &bBefore Line 2

**Comment by JustBru00** [comment]
I may want to add an alias such as `/ill` to make the command easier to use. Similar to the request in #123
