### ISSUE TITLE
Understanding Permissions and/or commands

### ISSUE THREAD

**Issue by thestudland** [JustBru00/RenamePlugin#119]
After a long while of looking at the so-called permissions page, I still have no idea how to configure this plugin so that other players that aren't op can use the rename function. Any idea on how to set this up?

**Comment by JustBru00** [comment]
The permissions are pretty straight forward. For each command there is a base permission that every player needs to access that command. Then there is per material and per format code permissions for most commands.
So to give /rename access to normal players they would need the following permissions:
`epicrename.rename`
`epicrename.rename.material.*`
`epicrename.rename.format.*`

The reason for this is to allow certain ranks to have different color/format code permissions.

Let me know if you have any further questions,
Justin

**Comment by thestudland** [comment]
Wait - so where do you specify these permissions? In the game or in the server properties? Or the config file? Do you write those permissions as is? Or does it require something else? I'm just confused about where to place the commands.

Thanks for answering quickly too and appreciate the help!

**Comment by JustBru00** [comment]
The permissions need to be placed in a permissions plugin like PEX or GroupManager. You will also probably need Vault https://www.spigotmc.org/resources/vault.34315/.

**Comment by thestudland** [comment]
Alright thanks! I had once wondered if this was something we might need as the solution for permissions. Thanks for the help!

**Comment by JustBru00** [comment]
No problem.

Let me know if you have any more questions,
Justin
