### ISSUE TITLE
Use with Anvil / Lock names behind permissions

### ISSUE THREAD

**Issue by MrXuiryus** [JustBru00/RenamePlugin#120]
Hi there

I'm currently trying to figure out a way to restrict my players from naming items certain names and lock them behind permissions. For example I want to make some custom elytra skins (which already work) but I don't want my players to be able to rename their elytra to "red elytra" to unlock the skin without first being given the permission to do this.

Is this possible with this plugin?

**Comment by JustBru00** [comment]
You can block players from using certain text in /rename. This would be done in the config.yml file in the `blacklists.text` section. The text is compared without color and in all lowercase.
```
blacklists:
  #Only player provided text is checked against the text blacklist. 
  #Use blacklists.existingname or blacklists.existingloreline to prevent players from 
  #editing already created items with certain text as part of their name or lore.
  text:
    - 'some_bad_phrase_here'
    - 'red elytra'
```

Keep in mind that this will not prevent players from using a vanilla anvil to rename the item.
