### ISSUE TITLE
[FEATURE REQUEST] Alias for /setloreline /removeloreline

### ISSUE THREAD

**Issue by SiuanSong** [JustBru00/RenamePlugin#123]
So this could be done with any plugin that can define alias', but I figured it'd be a nice addition to the actual plugin.
I recently added aliases **/sll** for /setloreline and **/rll** for /removeloreline and let me tell you, my life is 25% better because of it.  All my staff and players with access love it too!

**Comment by JustBru00** [comment]
This is a great idea. I will add it in the next version of the plugin.
