### ISSUE TITLE
[Suggestion] Add a command that hides enchantment flags

### ISSUE THREAD

**Issue by DeleteMetaInf** [JustBru00/RenamePlugin#133]
A command similar to /removeglow which would instead remove the enchantment text on an item would be very convenient.

This would be achieved by simply adding the `HideFlags:1` NBT tag, which hides enchantment text (such as “Efficiency III”), to the item.

**Comment by JustBru00** [comment]
So to be clear this command would hide enchantments on an item?

**Comment by DeleteMetaInf** [comment]
It would add the vanilla HideFlags:1 NBT tag, which hides the enchantment text in the tooltip of an item. However, it still glows.

**Comment by DeleteMetaInf** [comment]
Thanks for completing this. It’s been a while hah

**Comment by JustBru00** [comment]
> Thanks for completing this. It’s been a while hah

No problem. I am trying to catch up on old requests.
