### ISSUE TITLE
[Bug] /lore adds an extra space to the end of the text

### ISSUE THREAD

**Issue by DeleteMetaInf** [JustBru00/RenamePlugin#135]
Command used: `/lore &bTesting!`
![lore command](https://user-images.githubusercontent.com/59761487/73447229-93919580-435e-11ea-9b01-f6e7df6b5bd0.png)

Command used: `/setloreline 1 &bTesting!`
![setloreline command](https://user-images.githubusercontent.com/59761487/73447228-93919580-435e-11ea-82d4-97af64b3ef12.png)

****

As you can see, if /lore is used, it adds an unnecessary space to the end of the text, but this does not happen if /setloreline is used.

### Versions
* **Minecraft:** 1.15.2
* **[PaperMC](https://papermc.io/):** Build 82
* **EpicRename:** 3.7

**Comment by JustBru00** [comment]
Server Version: This server is running CraftBukkit version git-Spigot-800b93f-e911c70 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Bug proof: 
/lore: https://epicrename.com/2bc23d7992
/setloreline: https://epicrename.com/2f70964cd

Confirmed on EpicRename v3.7.
