### ISSUE TITLE
[Suggestion] Lore text above enchantment text

### ISSUE THREAD

**Issue by DeleteMetaInf** [JustBru00/RenamePlugin#136]
My feature request is new alternatives of existing commands (e.g., `/loreabove` and `/setlorelineabove`) to add lore text that appears directly underneath the item’s name rather than below enchantment text, if present.

This would be greatly useful. It was suggested by [HypersGamertag](https://www.spigotmc.org/members/hypersgamertag.105024) in his forum post referenced in #19, but I couldn’t find a specific issue created for this paritcular suggestion as the issue was about his other suggestion.

I’m not sure if this is possible. I’ve seen it done in mods, but mods can do anything, so I’m not sure if this is a possibility within vanilla Minecraft.

**Comment by JustBru00** [comment]
The only way I foresee this being remotely possible is to hide the actual enchantments on the item, then adding fake enchantment text to the bottom of any lore. How much if any this will break anvils etc is unknown.

**Comment by JustBru00** [comment]
Issue is resolved.
