### ISSUE TITLE
Lore deleting enchantments when used with CrazyEnchantments plugin

### ISSUE THREAD

**Issue by FourNineRugz** [JustBru00/RenamePlugin#142]
Title. Not sure if this is something that can be fixed with user configuration.

**Comment by JustBru00** [comment]
You can use the existing lore blacklist to prevent items from being renamed/relored if they have any crazy enchants.

https://github.com/JustBru00/RenamePlugin/wiki/Explanation-of-Blacklists-and-their-Usage#existing-lore-line-blacklist

You should also add the enchantments to the text blacklist to prevent players from adding their own enchants with /lore.
