### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by DarkDream15** [JustBru00/RenamePlugin#143]
Hi, I want to get help from you on something ı want to use your plugin in my server but ı having trouble blacklist,rename character limit and xp 
does not work even though I set. If you could help with this situation, I would greatly appreciate it I look forward to hearing from you have a nice day

**Comment by JustBru00** [comment]
Have you restarted your server after editing the config.yml file?

What server version are your ruunning? (/version)

What version of Ep[icRename are you using? (/epicrename version)

What is the contents of your config.yml file?

If you can provide that information I should be able to help you figure out what is going on.

Justin B.

**Comment by DarkDream15** [comment]
version 1.8.8
epicrename latest version
[aa.txt](https://github.com/JustBru00/RenamePlugin/files/4809443/aa.txt)
Banane , KimBilir , Yasak --The software of the words will be banned

**Comment by JustBru00** [comment]
Can you try renaming an item with those one of those words in the name with `/epicrename debug` enabled?

**Comment by JustBru00** [comment]
Closing issue due to no reply for the last 14 days. Will reopen issue if necessary.
