### ISSUE TITLE
MineableSpawners Issue

### ISSUE THREAD

**Issue by Gilthunderx** [JustBru00/RenamePlugin#144]
Hello , i have this bug that whenever my players rename their current spawners with the mob name they want to change it to, it somehow changed the mob type. Is there any fix about this. Like my player has a blaze spawner, then renames it to wither spawner. The spawner changed to wither.

Im using mineablespawner and epicrename.

**Comment by JustBru00** [comment]
Use the existing name blacklist to blacklist and the text blacklist to block spawner names.

https://github.com/JustBru00/RenamePlugin/wiki/Explanation-of-Blacklists-and-their-Usage

**Comment by JustBru00** [comment]
Closing issue due to no reply for 14 days.

**Comment by ImHumbug** [comment]
Hi, for a reason the spawner block on blacklist is not working

**Comment by ImHumbug** [comment]
my bad it's working but you have to capitalize all letters, spawner not working but SPAWNER does
