### ISSUE TITLE
/rename on an item makes the text italic (the slanted text) without me doing &o

### ISSUE THREAD

**Issue by ExpectedOracle** [JustBru00/RenamePlugin#147]
just as the title says, whenever i used to use /rename on the server i play on it would make the text straight and not in italics. But now after updating to 1.16 it makes it italics and the only way to not have it in italics is to clear the formatting with &r or to make it bold, but if i use &r i cant use colors.

**Comment by JustBru00** [comment]
Minecraft by default makes text italic. (&o) Just use &r as the start of the rename then add whatever extra color codes and text.

Example: /rename &r&bExample &eItem

**Comment by JustBru00** [comment]
This might be caused by: https://github.com/PaperMC/Paper/issues/3757. What is the output of the /version command?

**Comment by ExpectedOracle** [comment]
So this was totally my bad, sorry for the trouble. i had tried putting &r before it and it wasnt working but the problem was that we didnt know there was a 3.8 version so we were on 3.7. thanks for the help and im sorry again for bothering you! hope you have a nice day and keep up the great work with the plugin!

**Comment by JustBru00** [comment]
No problem.

Thanks for letting me know that you figured it out,
JustBru00
