### ISSUE TITLE
Add support for 1.16 HEX color codes

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#150]
Requested by `Geri#9999` on discord.

Requested by @CleCharge9731 on spigotmc.org.
https://www.spigotmc.org/threads/epicrename.51650/page-18#post-3873998

Requested by @danechek on spigotmc.org
https://www.spigotmc.org/threads/epicrename.51650/page-18#post-3882890

Also requested by MrWardy on spigotmc.org. 
https://www.spigotmc.org/resources/epicrename.4341/reviews#review-342958-309103

**Comment by JustBru00** [comment]
Requested by @CleCharge9731 on spigotmc.org.
https://www.spigotmc.org/threads/epicrename.51650/page-18#post-3873998

**Comment by JustBru00** [comment]
Need to decided on a syntax. Saw that some plugins are using `%55FFFF%`. to insert hex color codes.
Seems are good as anything. Another idea would be `&#55FFFF#` to stick with the current MC & system.

**Comment by datatags** [comment]
I've not seen the first one, and I've not seen the second one with the second #, personally I like &#FF0000 but I suppose with a closing # you could support short codes as well, &#F00#
Looking forward to this feature!

**Comment by JustBru00** [comment]
Requested by @danechek on spigotmc.org
https://www.spigotmc.org/threads/epicrename.51650/page-18#post-3882890

**Comment by JustBru00** [comment]
EssentialsX is using the same format for hex color codes.

Useful Regex: https://www.spigotmc.org/threads/hex-color-replacer-1-16.454402/

**Comment by JustBru00** [comment]
Worked on in: ca2fe19a53784ed1171504e23786b1267202318c
