### ISSUE TITLE
[Report] epicrename.poweruser doesn't have formatting permissions.

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#156]
https://www.spigotmc.org/threads/epicrename.51650/page-19#post-3974048
Reported by @Ajsmith0429

**Comment by SteeltonMC** [comment]
Cheers, just wish to add something. The Colors work, but things like Bold do not, with just epicrename.poweruser

**Comment by JustBru00** [comment]
Duplicate of #164. Fixed in 3.10.1. This issue is resolved.
