### ISSUE TITLE
./lore doesnt work even though player has perms

### ISSUE THREAD

**Issue by Dowritos** [JustBru00/RenamePlugin#158]
hey there, the command /lore does not work (it does but no perms)
even though a player has perms.
my perms set are: 

epicrename.lore
epicrename.lore.material.*
epicrename.lore.format.*

Is there something i forgot?

**Comment by Dowritos** [comment]
lol nvm i litteraly looked at my parent settings for groups, turns out my parent for that group was not set correctly! LMAO

**Comment by JustBru00** [comment]
Glad you got it figured out.
