### ISSUE TITLE
Hex codes not displaying

### ISSUE THREAD

**Issue by pudgio** [JustBru00/RenamePlugin#163]
Currently using Paper-79 for 1.17 and version 3.9 of EpicRename. When using the /rename command with a hex code after, the item that I chose to rename does not show the chosen hex color. ie. /rename &#ff0000Sword
The item name shows up as &#ff0000Sword and not 'Sword' with that hex color(which is bright red).
Testing this with all EpicRename permissions granted to my LuckPerms user group.

**Comment by JustBru00** [comment]
This is due to EpicRename version 3.9 not knowing about minecraft 1.17. 
This was fixed in issue #160. 
I have a release candidate of EpicRename version 3.10 that fixes this issue if you would like to try it out.
https://github.com/JustBru00/RenamePlugin/releases/tag/v3.10-RC2

**Comment by pudgio** [comment]
Thank you, updating my server now.
