### ISSUE TITLE
[Feature Request] Edit Lore Line and Name

### ISSUE THREAD

**Issue by SiuanSong** [JustBru00/RenamePlugin#168]
If this is even at all possible, I'd like to see the ability to edit preexisting lore lines or names. Something that could copy the existing lore including format and colors into the chat box for editing. I've seen other plugins do this with signs so I assumed there might be a way to do this with lore as well. 

Sometimes after completing an item we need to edit it or fix the spacing. It'd be extremely handy to just be able to edit the line instead of retyping the entire thing.

**Comment by JustBru00** [comment]
This is possible. I think a workflow similar to the following would work.
New command /editlore which sends the player a chat message they can click on. This clickable text suggests a /lore command that is already filled out with the lore from the item in hand.

**Comment by JustBru00** [comment]
Possible command layout:
`/editlore` `/editname`

**Comment by SiuanSong** [comment]
Yay! This is awesome! Thanks so much <3
While this will come in super handy and I appreciate the work you put into it, most of our lores don't really fit in a single /lore command, so it only does partial lores. 
I was thinking more along the lines of like **/editloreline #** to be able to edit just a single line

**Comment by JustBru00** [comment]
I have created a new issue to track progress on this feature.
