### ISSUE TITLE
Legacy Gradients

### ISSUE THREAD

**Issue by sirblazzit** [JustBru00/RenamePlugin#174]
I removed players' permission to use hex codes in order to make gradients not possible,.. but they've found a way around it by using the 'Legacy' preset on RGB Birdflop. I don't want to limit the amount of formatting because people sometimes have long item names where every letter is a different color. How do I turn off what I assume is &x?

**Comment by JustBru00** [comment]
It appears `&x&r&r&g&g&b&b` is an internal way of representing hex color codes within bukkit/spigot.
I think it was added around 1.16 when hex color codes were added.
I think the best option is to add a config option to block `&x`.
This will prevent players from using `&x` to circumventing the hex color code permissions.

**Comment by sirblazzit** [comment]
Awesome!
