### ISSUE TITLE
Rename or Lore makes a choice (bug?)

### ISSUE THREAD

**Issue by Kooda026** [JustBru00/RenamePlugin#177]
Hello, I have a minecraft VQS server hosted at Verygame which is in version Mohist-1.16.5. I want to open it as a Medieval Role-play server

With: 20 plugins and 8 mods

Here is my problem:

When I want to rename an item and put a lore to it with the help of EpicRename plugin, if I start by renaming, the item I can put it no worries, the item changes its name, but when I want to add a lore to this item. Its lore is not displayed.

When I do the reverse, first the lore and then the name, the lore is put well, but the name does not change.

Can you help me?

**Comment by JustBru00** [comment]
I just tested this on paper 1.19.3 with EpicRename version 3.11.1. 
![image](https://user-images.githubusercontent.com/11063799/235545314-7713fcad-9262-4693-8021-2b1f45ef2b1d.png)

Both the name and lore are visible. I would guess that this is an issue with Mohist.

![image](https://user-images.githubusercontent.com/11063799/235545386-9ce0ce73-0960-404a-a55c-34430e52a846.png)
![image](https://user-images.githubusercontent.com/11063799/235545402-5cf78113-897f-4e52-ba11-4f92be5c4ce5.png)
![image](https://user-images.githubusercontent.com/11063799/235545412-5506d9d3-4733-4d73-8ade-76ea366eef9c.png)
