### ISSUE TITLE
Permisions to players

### ISSUE THREAD

**Issue by Kolagohoh** [JustBru00/RenamePlugin#178]
Hi i have a problem, i only op human on my server but i want to my firends can use comands too,what i need to change in config to give permisions to use commands? my server on paper 1.19.2

**Comment by JustBru00** [comment]
You will need to add a permissions plugin to your server such as LuckPerms.
After you have a permissions plugin, the permissions are listed at: https://github.com/JustBru00/RenamePlugin/wiki/Permissions-List
