### ISSUE TITLE
Location of Data saving File 

### ISSUE THREAD

**Issue by AnimeNymphe** [JustBru00/RenamePlugin#183]
Hello there, can you please tell me, where i can see the database of the renamed items in Epic Rename Plugin? After updating the MC-Server (we are using Paper) to the latest version of Minecraft, all of our renamed items are missing (the names/data).  There is no data in /stats in plugin-folder or else and the renamed items are still renamed, even when we deinstalled the plugin. So thats why we are wondering, why have the renamed items still the "new" name and if there is a database in a other folder than the epic renamed-plugin-folder (where can we find the folder with a list of the renamed items) kind regards

**Comment by JustBru00** [comment]
EpicRename does not create a database of renamed items. EpicRename changes an items display name and lore. These changes are stored in the vanilla world save files.

If your items are missing, it sounds like your world may have been corrupted.

**Comment by AnimeNymphe** [comment]
Hey, do you by chance know where the vanilla world save files are, where the changes are stored? Because we copied the world before updating to 1.20 and and after updating the version it was no data of the plugin anymore. Everything else is there, only the renamed items are missing.

**Comment by JustBru00** [comment]
https://wiki.vg/Map_Format

**Comment by AnimeNymphe** [comment]
Thank you so much for your help so far. I hope we can find the issue here and we are looking for the time, when we can rename our items like we did before. And thank you for the great work with Epic Rename :3 We like this Plugin and your work very much <3
