### ISSUE TITLE
Shulker Boxes losing their name on pickup.

### ISSUE THREAD

**Issue by AeloniMC** [JustBru00/RenamePlugin#190]
Unsure if this is something that could be answered here, but it's worth a shot.
Lately on our server, shulker boxes don't keep their name after you place them and pick them back up. It still shows the name when it's placed as if it worked as normal, but once you pick it up, it goes back to the default name. Any idea what the issue could be?
We have EpicRename as a plugin, but whether you use /rename, /anvil, or a physical anvil, you get the same result. Any idea what the issue could be?

**Comment by JustBru00** [comment]
What is the output of /version?

**Comment by AeloniMC** [comment]
version 3.11.1

**Comment by JustBru00** [comment]
No /version from the minecraft server.

**Comment by AeloniMC** [comment]
Oh lmao my fault.
![image_2024-01-28_231123649](https://github.com/JustBru00/RenamePlugin/assets/158012768/b154938f-4fb4-4b0c-81a9-fb856bc2f452)

**Comment by JustBru00** [comment]
Cannot reproduce with paperspigot 1.20.1 Build 196. Try reproducing with paper instead of pufferfish.
![image](https://github.com/JustBru00/RenamePlugin/assets/11063799/a3508b13-7082-4783-87d4-b12b435452d0)
