### ISSUE TITLE
disable_bypass_messages not working for economy

### ISSUE THREAD

**Issue by Pirito10** [JustBru00/RenamePlugin#195]
Having `disable_bypass_messages: true` does not disable the message `economy.bypass`

Server version: git-Purpur-2176 (MC: 1.20.4)
EpicRename version: 3.12
Java 21

To replicate:

1. Use default config.yml
2. Set `disable_bypass_messages` and `economy.use` to true
3. Give yourself permissions `epicrename.rename.*` and `epicrename.bypass.costs.*`
4. Give yourself some money
5. Run `/rename` on any item

The message from node `economy.bypass` ('&aYou just bypassed the economy requirement.') will show

**Comment by JustBru00** [comment]
@Pirito10 I am very busy with work right now. Not sure when I will make this release public. You can download a snapshot release at: https://github.com/JustBru00/RenamePlugin/releases/tag/v3.12.1-snapshot%2B2024.may.24

**Comment by Pirito10** [comment]
Alright thank you so much!
