### ISSUE TITLE
Feature Request: Add support for ' ' in commands

### ISSUE THREAD

**Issue by tuanjr** [JustBru00/RenamePlugin#30]
Please add support for space, so player don't need use _ to show "space"

**Comment by JustBru00** [comment]
I will try and add this in the next update. Currently I have a concussion so I can't look at screens very long. I will make it as soon as possible.

**Comment by JustBru00** [comment]
Also requested by @Spicerfire on spigotmc.org

**Comment by JustBru00** [comment]
Changed to Version 3.0 as it will be hard to add in current code.

**Comment by JustBru00** [comment]
Mostly finished in Version 3.0-ALPHA-DEV. Waiting to closed until further testing can be done.

**Comment by JustBru00** [comment]
@tuanjr Check out the release. https://github.com/JustBru00/RenamePlugin/releases/tag/v3.0
