### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by Fancepants** [JustBru00/RenamePlugin#49]
I given all perms to my loreteam group and nothing seems to be working I want to give them access to all permissions epicrename.rename.* not working

**Comment by JustBru00** [comment]
Could you please send me your config.yml, your current minecraft server version, and the version of the plugin you are using? Also could you send your permissions plugin's permissions file.

**Comment by JustBru00** [comment]
@Fancepants It appears like github is having some issues so that is why it said you added those labels.
Please read the message above for help with your problem.

**Comment by Fancepants** [comment]
I got this fixed now , seems to be just an issue with the lines now /lore Line2 will not add it correctly

**Comment by JustBru00** [comment]
The /lore command creates a new line after every space. So /lore Stuff and_more_stuff
Would appear on the item like this:
```Stuff
and more stuff```

This will be changing to a better system in version 3.0.
