### ISSUE TITLE
Compatibility with Crazy Enchants

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#63]
https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/updates

Will require some craziness to work.

Submited: https://www.spigotmc.org/threads/epicrename.51650/page-7#post-2275424

**Comment by JustBru00** [comment]
Possibly a Crazy Enchants mode?

**Comment by tyler489** [comment]
Crazy enchants requires the color of the lore to match prehaps add another permission node to be able to use colored lore

**Comment by JustBru00** [comment]
That is a good idea. Then the server owner could use the permissions from #21 to prevent making fake enchants.

**Comment by JustBru00** [comment]
This will be closed when #21 is complete.

**Comment by JustBru00** [comment]
Closing this as #21 is complete.

**Comment by JustBru00** [comment]
Technically, this does not solve the original problem. However I cannot think of a way to actually create a "hook" to detect enchants without a lot of work. As such this will be closed until a different solution is found.
