### ISSUE TITLE
[REQUEST] Per world plugin enabling and disabling

### ISSUE THREAD

**Issue by BrettplayMC** [JustBru00/RenamePlugin#67]
Per world support.

**Comment by JustBru00** [comment]
I assume you mean per world enabling/disabling support.

**Comment by BrettplayMC** [comment]
Well I mean full per world support.  So if a player isn't in X world(s) then they receive a custom message and nothing happens.

**Comment by JustBru00** [comment]
Okay we are both on the same page then 😄

**Comment by JustBru00** [comment]
@BrettplayMC Would you like it by permissions or a config option?

**Comment by JustBru00** [comment]
Developing it as a config option.
