### ISSUE TITLE
/name copy

### ISSUE THREAD

**Issue by DoubleThePsycho** [JustBru00/RenamePlugin#73]
Add /name copy
Add /lore copy
Allow for the copied items to be saved in clipboard and pasted into other programs

**Comment by JustBru00** [comment]
Are you saying pasted by this plugin also?
Like /epiccopy would paste it in the config file
Then on another server you could /epicpaste name


This would probably be a separate plugin. I don't want EpicRename to get too bloated.

**Comment by JustBru00** [comment]
#86 Appears to be what you want. That is also related to #29

**Comment by JustBru00** [comment]
I will close this issue as it will be handled by #86 and #29.
