### ISSUE TITLE
Error report for 1.12

### ISSUE THREAD

**Issue by SadieICN** [JustBru00/RenamePlugin#74]
I am trying to add this plugin to my 1.12 server but when I try to use it I get an internal error

**Comment by JustBru00** [comment]
What is the error you are getting? Could you please paste it here.

**Comment by SadieICN** [comment]
17.06 14:39:06 [Server] INFO SadieICN issued server command: /rename test
17.06 14:39:06 [Server] ERROR null

**Comment by SadieICN** [comment]
It is only the /rename command that is not working. Everything else is working

**Comment by SadieICN** [comment]
It was conflicting with another plugin I had. I have fixed it

**Comment by JustBru00** [comment]
Okay. Glad you figured it out.

Closing because problem is resolved.
