### ISSUE TITLE
[REQUEST] Check Existing Name/Lore for Match in Config, Prevent Name/Lore Change

### ISSUE THREAD

**Issue by hoorigan** [JustBru00/RenamePlugin#81]
My community would like to see a feature that disallows the name and lore changes on items with names or lores that match specific strings?  We are seeing an issue where a player can change the lore on a pickaxe with a mcMMO ability toggled, and the ability stays permanently toggled.

So, for example, we want the ability to prevent a user from changing the name or lore on an item that has 'mcMMO Ability Item' or 'mcMMO Item' in its lore.  As of right now, there are no name/lore plugins with this option, and it prevents us from allowing players to change the names and lores on their items.

Thanks in advance for looking into this.

**Comment by JustBru00** [comment]
Hey there. This definitely is a possible feature to add. I will add it to the version 3.3 milestone. I will try and finish this as soon as possible. Quick question: Do you need the "blocked" item lore text to be case sensitive? Does mcMMO only recognize 'mcMMO Ability Item' or does it also detect 'mcmmo ability item'?

- JustBru00

**Comment by hoorigan** [comment]
I’m honestly not sure- I’d have to look over mcMMO’s source code to see how they do the string matching.  To make it case insensitive might be the safer route, though, as this feature should increase compatibility with any plugin that uses string matching in names or lores.  We have a few plugins that do things that way, some of which don’t have their source code readily available.  Better to be too greedy with the match than not, I think.

**Comment by JustBru00** [comment]
I will just make it check as case insensitive. 

Thanks for the quick reply,
Justin

**Comment by JustBru00** [comment]
- [X] /rename
- [ ] /lore
- [ ] /setloreline
- [ ] /removeloreline
- [ ] /glow
- [ ] /removeglow

**Comment by JustBru00** [comment]
Blacklist is working as expected with /rename

**Comment by JustBru00** [comment]
Working as expected with /setloreline
