### ISSUE TITLE
Blacklist Enchantment Lores by default

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#82]
Requested by @Cobwebster on spigotmc.org

https://www.spigotmc.org/conversations/epicrename.273324/

**Comment by hoorigan** [comment]
+1

**Comment by JustBru00** [comment]
Cannot reproduce issue. I have messaged @Cobwester on spigotmc.org.

**Comment by JustBru00** [comment]
I am going to close this issue as the problem can be solved by blacklists.existingname and blacklists.existinglore
