### ISSUE TITLE
EpicRename Issues

### ISSUE THREAD

**Issue by KGKhan1** [JustBru00/RenamePlugin#89]
Hello.

I've installed the plugin 'EpicRename' coded by you. I gotta tell you, the plugin itself is great but I'm encountering some issues while using the plugin. First of all, I've changed the plugin prefix and reloaded the plugin but nothing changed. Please fix that. Second of all, the blacklists don't work (at least for me, doesn't work). Players can rename anything to something that is blacklisted (text), even with the negated permission node for the blacklist bypass. Please fix this, too.

Thanks.

**Comment by JustBru00** [comment]
Can you send me a copy of your config and any permissions you have given the players?
Blacklists will be bypassed if you are a operator on the server, so that could be part of the issue.

I have a feeling this is a config issue. I have tested every feature and confirmed that they work correctly.

**Comment by KGKhan1** [comment]
No, I've tested out the blacklists as an original player. I've removed the permission node (although the group didn't have it) 'epicrename.bypass.textblacklist' and added the permission node '-epicrename.bypass.textblacklist'. However, they were still able to use /rename (with permission node) to something blacklisted. My config can be seen here: https://hastebin.com/ijajofociv.bash. Please tell me why my prefixes aren't working too.

**Comment by JustBru00** [comment]
Are you trying to block the renaming of an existing item? Or are you trying to block the using of /rename to create an item with the name of `&2&lHulk &a&lSmash`? The text blacklist is only checked when a player attempts to edit a item with a command. The existing name blacklist prevents players from editing an existing item that has a certain name.

**Comment by JustBru00** [comment]
As for your prefix can you tell me what the plugin displays in console on startup?

**Comment by KGKhan1** [comment]
Nevermind, the prefix is fixed. Sorry about that. For the BlackList, I was trying to prevent players from renaming items to '&2&lHulk &a&lSmash'. If that's not the proper method of preventing this issue, what is the proper method?

**Comment by KGKhan1** [comment]
Yep, sorry. Here it is:





2018-08-11 11:20 GMT+09:00 Justin Brubaker <notifications@github.com>:

**Comment by JustBru00** [comment]
Your picture did not come through. Try posting right on github instead of replying to the email.

**Comment by KGKhan1** [comment]
![image 1](https://user-images.githubusercontent.com/40845515/44032142-440417da-9f41-11e8-8462-04c6681634fa.png)
![image](https://user-images.githubusercontent.com/40845515/44032145-45a06d1e-9f41-11e8-8c52-fff6bc5b9b43.png)

**Comment by JustBru00** [comment]
Try removing color codes from the text blocked in your config. So that it reads: `Hulk Smash`

**Comment by JustBru00** [comment]
Have you had any success with figuring out this issue?

**Comment by KGKhan1** [comment]
Yes, it works fine now! Thanks

2018년 9월 21일 (금) 오전 2:59, Justin Brubaker <notifications@github.com>님이 작성:

**Comment by KGKhan1** [comment]
Hey,

I just signed the petition "Shut Down the Yulin Dog Meat Festival in Yulin,
GuangXi China" and wanted to see if you could help by adding your name.

Our goal is to reach 4,500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/qqJMWRSKWj

Thanks!
Jenewoo

**Comment by JustBru00** [comment]
No Advertising.
