### ISSUE TITLE
A mystical force prevents me from renaming things

### ISSUE THREAD

**Issue by APimpNamedShane** [JustBru00/RenamePlugin#91]
but I can add lore and make them glow just fine.

My permissions is PermissionsEx:

    - epicrename.bypass.materialblacklist
    - epicrename.bypass.textblacklist
    - epicrename.bypass.costs.*
    - epicrename.rename
    - epicrename.rename.format.*
    - epicrename.rename.material.*
    - epicrename.rename.*
    - epicrename.lore
    - epicrename.lore.material.*
    - epicrename.lore.format.*
    - epicrename.setloreline
    - epicrename.removeloreline
    - epicrename.glow
    - epicrename.removeglow

**Comment by JustBru00** [comment]
Can you try doing /epicrename debug then trying to rename something? I need a screenshot of the [DEBUG] text

**Comment by APimpNamedShane** [comment]
![2018-09-18_19 41 03](https://user-images.githubusercontent.com/35150729/45724261-e0663900-bb7a-11e8-884f-2aaabc2f0cc1.png)

**Comment by JustBru00** [comment]
What plugins are installed on your server?
That message is not in EpicRename.

**Comment by JustBru00** [comment]
Try removing non common plugins. I don't know of any common plugins with that message

**Comment by APimpNamedShane** [comment]
Stables plugin has a /rename function that conflicts with EpicRename's. For the time being I have switched to a different hourse plugin, but would be interested in a version using a different command than /rename to rename items, such as /erename.  Thanks.

**Comment by JustBru00** [comment]
You can use /epicrename:rename for now. I have created an issue. (#92)
