### ISSUE TITLE
[Request] Set Maximum Allowed Lines for /setloreline

### ISSUE THREAD

**Issue by SiuanSong** [JustBru00/RenamePlugin#95]
Hi again!
I'd like to be able to limit the amount of lines one player can do.  For example, someone on our server did /setloreline 1000 [text].  Subsequently, the item they lored caused that person to go into a crash loop.  Staff had to clear inventory of said player.  I'd like to prevent this from happening again.
Thank you,
Siuan

**Comment by JustBru00** [comment]
That is a great suggestion. I will add it to the TODO list.

**Comment by SiuanSong** [comment]
Awesome! thank you!

**Comment by jayoevans** [comment]
@SiuanSong What version of Minecraft was this on? I'm testing this currently and had no issues setting lore lines up to 1000 on 1.13.1.

Sounds to me like an older version issue.

I'd be happy to fix this issue, though I doubt the author would appreciate me putting a hard-cap on the max line number if this isn't an issue in newer Minecraft versions.

@JustBru00 Thoughts?

**Comment by JustBru00** [comment]
Personally I was thinking a config option. 

Eg. `max_setlore_lines: 20`
I think it is just as important as a purely astetic feature.

Even if Minecraft can handle it, I want to be able to read the whole lore on the screen.

**Comment by SiuanSong** [comment]
It was on 1.12.2 for reference.  I believe it happened when someone put a lot of lore on the item. Full lore lines way past what the actual lore will show.  I think the data size of the item was so big that it just crashed anyone who looked at it.

**Comment by JustBru00** [comment]
Closed by 3209266afbccdf7467b96abfd052ab1da77a7363

**Comment by JustBru00** [comment]
Note for update credits: @jayoevans is @Sobki on spigotmc.org.
